### ISSUE TITLE
Unable to Upload Multiplayer Game

### ISSUE THREAD

**Issue by MaikelFritz** [yairm210/Unciv#12997]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Game Version

4,15.12

### Describe the bug

Unable to upload game in Multiplayer Mode
Error Popup occurs.. No way to end a round.

### Steps to Reproduce

1. Go to Next Round

### Operating System

Android

**Comment by Green-Sky** [comment]
@touhidurrr sorry for tag, but this has pretty much deadlocked a game for me for 2 days now.

**Comment by Vanadium-GITHUB** [comment]
I am also having this issue myself. ^^^

**Comment by touhidurrr** [comment]
@Green-Sky @Vanadium-GITHUB cannot reproduce the issue.

**Comment by Green-Sky** [comment]
Right, for me the notification(?) state is a different turn the the actual savegame. So you are looking for games that have inconsistent "next turn" state.

**Comment by Vanadium-GITHUB** [comment]
Unsure if this will help but here is my save game. 

https://github.com/[Vanadium-GITHUB/unciv-save-game](https://github.com/Vanadium-GITHUB/unciv-save-game)

![Image](https://github.com/user-attachments/assets/b81dad6d-251f-4550-96b0-c819c1494b2d)

I considered if it was an issue with mods, but OP is receiving the same error playing without mods.

**Comment by touhidurrr** [comment]
By the way, the server has a filesize limit. Are you sure you guys did not exceed it?

**Comment by Vanadium-GITHUB** [comment]
@touhidurrr that must be it. What is the limit?

**Comment by Vanadium-GITHUB** [comment]
@yairm210 Our save was 1.28 MB

**Comment by touhidurrr** [comment]
The server file size limit is 1MB. I am planning to increase this to 2MB next month following the automatic system upgrade to MongoDB Flex. MongoDB Atlas seems to be moving to a new pricing structure and our instance will be automatically migrated to Flex with a 150% increase in storage without any noticeable increase in cost.
I think I will increase the file size limit at that time because bigger games seems to be gaining some weird popularity recently and with an average file size of <100KB, this should not affect the server much.

**Comment by touhidurrr** [comment]
> @yairm210 Our save was 1.28 MB

Save or JSON?

**Comment by touhidurrr** [comment]
Also, do you guys use discord? Can you run a `/gameinfo` command on your game and show us the output?

**Comment by Green-Sky** [comment]
> Also, do you guys use discord? Can you run a `/gameinfo` command on your game and show us the output?

No, but I asked a friend, and the command just times out (pm).

**Comment by Green-Sky** [comment]
What is a savefile. I said json, because the autosave file contains json.

**Comment by touhidurrr** [comment]
Ok, I guess I will just increase the limit to 2MB now, since march is near anyways. And its not like we are currently in any low disk space situation.

![Image](https://github.com/user-attachments/assets/a16a098c-4299-48cf-8a0a-476ff1f23ce1)

Done with https://github.com/touhidurrr/UncivServer.xyz/commit/58b8c3b7e65566de6e23af06953f1a9b3ad32776

**Comment by touhidurrr** [comment]
@Green-Sky @Vanadium-GITHUB let me know if this fixes your issues.

**Comment by Hoernla** [comment]
I haven't written before, but have watched this thread from the start, experiencing the exactly same problems. In our game, the road is still bumpy. That means, when I finish my turn, it seems not to work, upload is not confirmed, the next player is not shown in the main screen as "waiting for". 
At some point in time, this might switch. Until then, however, reloading the game allows me (forces me?) to make this turn once more. 

All the while, when I go to the "Multiplayer" menu, there is still another player's turn from a week ago shown as current. When I want to pass this turn, a message comes telling me I cannot pass him as the current player has been updated. However, sometimes it shows the actual current player but will jump back.

**Comment by Green-Sky** [comment]
Issue persists, no change. @Hoernla did describe it nicely.

**Comment by touhidurrr** [comment]
> Unsure if this will help but here is my save game.

[https://github.com/[Vanadium-GITHUB/unciv-save-game](https://github.com/Vanadium-GITHUB/unciv-save-game)](https://github.com/%5BVanadium-GITHUB/unciv-save-game%5D(https://github.com/Vanadium-GITHUB/unciv-save-game))

I dont know where issues like this are popping  up from but I just entered this game and made a turn as Korea without any problem. So, yet again, cannot reproduce any issue.

**Comment by touhidurrr** [comment]
>  At some point in time, this might switch. Until then, however, reloading the game allows me (forces me?) to make this turn once more.

Looks like a client issue to me @yairm210 .

**Comment by touhidurrr** [comment]
Also, one this for sure that you guys are not updating your clients often. Which can also lead to weird issues. @Vanadium-GITHUB

**Comment by Hoernla** [comment]
I added a txt to upload. 
Now we know that we infrequently update (at least those on windows, half of us use android), however we all updated as soon as we ran into this problem.

[autosave.txt](https://github.com/user-attachments/files/19032853/autosave.txt)

**Comment by touhidurrr** [comment]
> however we all updated as soon as we ran into this problem.

Does this mean you guys are all still facing the problem even after updating? That being said, what is the issue exactly? I tried playing your game and made a turn in it successfully without any issue. Have you guys noticed this?

Also, where do you guys live?

**Comment by Vanadium-GITHUB** [comment]
@touhidurrr @yairm210 Updating to current client works! Thank you for the help and sorry for the trouble. =)

**Comment by Green-Sky** [comment]
> Also, where do you guys live? Can it be that the issue happens in your region only.

Central Europa.

> Now we know that we infrequently update (at least those on windows, half of us use android), however we all updated as soon as we ran into this problem.

Similar too us. Really funny how the problem suddenly popped up for a wide range of versions.

I still think it's weird that it sometimes works, despite the "upload failed" error. But the update status(preview file?) has not been updated in 7 days.

**Comment by MaikelFritz** [comment]
Hey - thank you very much for your quick help. I wasnt able to respond during the week due to heavy workload. 
The problem however still persists. I cant end my turn. I am located in Germany and all players are using android systems. 
Ive checked my version - I am using the current version 4.15.13
game-id is f0fd7e28-b472-419e-bc85-3c62f78309c4

would it be safe to start a smaller game or could it occur there as well. 
thanks for your help and your good work on this game! appreciate it very much!

**Comment by Hoernla** [comment]
Germany as well. As I said we updated as soon as we ran into the issue to 4.15.12

Game-IDs are:
d5890572-b7bb-4ad0-858e-8bc276481c90
b92cdb39-6003-42fc-841c-5e8729cee386

We are on https://uncivserver.xyz

**Comment by touhidurrr** [comment]
Ok, @yairm210, I can finally reproduce the issue a bit and can guess why this is happening. Look as the screenshot below:

![Image](https://github.com/user-attachments/assets/c75fdedb-5d32-4080-b81a-c18d7dce0e87)

Ignore the debug log in the last line. It just shows first 100 characters of the save and true means the game file was not corrupted (can be unpacked). but what is noticeable here is not the presence of something but the absence of something. The client here is uploading the game file properly but never trying to upload the Preview file. Which is weird. This leaves the preview file to be always outdated. And yes, this can be reproduced. (try with gameId `d5890572-b7bb-4ad0-858e-8bc276481c90`) So, now we have 2 reasons why this might be happening:
1. uploading Preview files is failing for some reason.
2. the client cannot upload the preview file for some reason,

I am looking into possibility 1 for now.

**Comment by touhidurrr** [comment]
Ok, after much testing, I have come into the conclusion that it is probably a client issue. Maybe in certain situations Preview files generation fails. As, from what I can see from logs, an attempt to upload the file was never made to begin with. Let me know, what was the issue if you figure it out @yairm210 .

**Comment by touhidurrr** [comment]
Ok, it took me a packet-capturing software to figure out what was going on. However, the problem seems to be some faulty validation issue. This was the fix:

![Image](https://github.com/user-attachments/assets/06f80cee-b265-43d0-9ea7-da4a59cc2316)

Here, `'byte'` is supposed to mean `'base64,'` and it worked as far as I know. But for some reason, for certain uploads, this validation seems not to work and the response results in a validation error. This kind of validation was there to prevent corrupted game files to uploaded to the server, but it broke and I am not sure why. Thankfully we do not need this now because we now check if the save file is a proper JSON-gzipped-base64 file somewhere else in the codebase. So, we do not need to check it here also. The cause might be this validation being broken in the library I am using for some reason. But then again, why does this issue happen so rarely? And for some games it happens and for some other games not. Sigh.

Anyway, the issue should be fixed now. But it is also true that if the error messages were a little more helpful, maybe I would not have required WireShark to debug it. Why do I need to use my cybersec knowledge to debug a silly issue? Sigh.

@Green-Sky @Vanadium-GITHUB @Hoernla kindly check and report if the issue still persists.

**Comment by yairm210** [comment]
Wow, excellent hunting! 
I wonder if I can add client side validation that indeed the preview and actual save are equivalent, in i.e. turn number... 🤔

**Comment by touhidurrr** [comment]
> I wonder if I can add client side validation that indeed the preview and actual save are equivalent, in i.e. turn number... 🤔

Not sure what that will solve. In the end I found out that the client was not indeed working properly. So, changing its behaviour might result in unforeseen circumstances. Maybe we should fetch the full game file once in a while also. Like one in 20 refresh probably? But that feels useless also.

**Comment by touhidurrr** [comment]
I guess you misunderstood why this happened. For some rare cases, for unknown reasons, the base64 validation failed. So, even when I manually tried to hit the api with made up requests everything was ok. And I needed installed WireShark to verify my doubts.

Preview files were not the issue. The uploading of the main save files were failing in a way I was unable to figure out how. And that's why the client never attempted to upload preview files. So, in the end, the issue was very random and did not happen consistently enough for me to reproduce it. Not an issue with the client.

**Comment by touhidurrr** [comment]
Anyways, if nobody replies within a couple of days then I guess the issue is solved.

**Comment by Green-Sky** [comment]
Complication.

The current player (A) can't do his turn, because for him it shows that it is player (B)'s turn (player according to preview file). Every other player, when loading the game, sees that it is player (A)'s turn instead, so we are deadlocked again.
The issue arose actually before the fix yesterday, but it still is like this.
Player (A) tried versions 4.15.13 and 4.15.14 .

When I load the game with 4.15.12, 4.15.13 or 4.15.14, it shows me that player (A) has to do the turn.

**Comment by touhidurrr** [comment]
> Game-IDs are:
d5890572-b7bb-4ad0-858e-8bc276481c90
b92cdb39-6003-42fc-841c-5e8729cee386
> 
> We are on https://uncivserver.xyz

Game 1: I just made a turn as China with no issues.
Game 2: I made a turn with Inca with no issues.

Both from latest Android version.

SO THE ISSUE HAS BEEN FIXED!! If not give me something that I can reproduce. From what I can see, all the games you dropped ids for is working properly now. If a particular game is not then give us the id to debug.

**Comment by touhidurrr** [comment]
By the way, I also saw that China made a turn 10 minutes ago. So, the issue should have been fixed?

**Comment by Green-Sky** [comment]
> Complication.

> The current player (A) can't do his turn, because for him it shows that it is player (B)'s turn (player according to preview file). Every other player, when loading the game, sees that it is player (A)'s turn instead, so we are deadlocked again.
The issue arose actually before the fix yesterday, but it still is like this.
Player (A) tried versions 4.15.13 and 4.15.14 .

> When I load the game with 4.15.12, 4.15.13 or 4.15.14, it shows me that player (A) has to do the turn.

@yairm210 My issue seems to be a new deadlock, which I really don't know how to debug/if it's possible to debug, since I don't have access to the friends device. What would happen if I pressed, "skip turn of current player" ?

@touhidurrr Sorry, can't test at the moment... but I have high hopes :)

**Comment by touhidurrr** [comment]
> according to preview file

From what I can see, the main and preview save files for the games that you shared are not de-synchronized now.

>  The issue arose actually before the fix yesterday, but it still is like this.

Then I dont think that is relevant. Kindly, don't share old bugs without verifying if they still exists.

> can't test at the moment.

Kindly, let us know if everything is fixed now when you have time to test.

**Comment by touhidurrr** [comment]
I asked discord, who were playing a 17 person game or something like that and facing the same issue. They are not facing any issue currently.

![Image](https://github.com/user-attachments/assets/f770b768-b402-48d2-bce5-be0a213a9f3f)

**Comment by Green-Sky** [comment]
> > according to preview file
> 
> From what I can see, the main and preview save files for the games that you shared are not de-synchronized now.

I did not post a save / game-id, so you are confusing me with someone else here.

> > The issue arose actually before the fix yesterday, but it still is like this.
> 
> Then I dont think that is relevant. Kindly, don't share old bugs without verifying if they still exist.

As I said, It still exists and the reason why I can't test the fix.

**Comment by touhidurrr** [comment]
> I did not post a save / game-id, so you are confusing me with someone else here.

oh sorry, i thought you guys were playing the same game. anyways, if you dont want to post game-ids here, then you can dm me on discord.

> As I said, It still exists and the reason why I can't test the fix.

It's hard to debug it without any clue.

**Comment by touhidurrr** [comment]
> can't test at the moment.

Also, I assumed that you did not try after the fix because of this comment.

**Comment by Green-Sky** [comment]
> > I did not post a save / game-id, so you are confusing me with someone else here.
> 
> oh sorry, i thought you guys were playing the same game. anyways, if you dont want to post game-ids here, then you can dm me on discord.

I don't have discord, but I am tasking one of the game's participants.

> > As I said, It still exists and the reason why I can't test the fix.
> 
> It's hard to debug it without any clue.

Yea, especially since I personally don't have access to that persons device.
Fun things happen when preview files and safe files don't align ...

**Comment by Green-Sky** [comment]
> > > I did not post a save / game-id, so you are confusing me with someone else here.
> > 
> > 
> > oh sorry, i thought you guys were playing the same game. anyways, if you dont want to post game-ids here, then you can dm me on discord.
> 
> I don't have discord, but I am tasking one of the game's participants.
> 
> > > As I said, It still exists and the reason why I can't test the fix.
> > 
> > 
> > It's hard to debug it without any clue.
> 
> Yea, especially since I personally don't have access to that persons device. Fun things happen when preview files and safe files don't align ...

Ok, so, the problem was resolved. tldr: skipping current turn updated the preview, without actually skipping, then the player could do his turn. No issue after that.


> Anyways, [@yairm210](https://github.com/yairm210), I think we can safely close this and [#12998](https://github.com/yairm210/Unciv/issues/12998) now. From what I can see things has been fixed now. With not enough evidence to support otherwise. New bugs need new issues.

I agree, looks like the issue is resolved.

Some form of validation to detect or properly handle out-of-sync preview files would be nice in the future.

**Comment by yairm210** [comment]
Ok
I added a 'copy stacktrace to clipboard' so in future errors it will be easier to debug

**Comment by MaikelFritz** [comment]
Thank you very much! Game is running like a charm again!

**Comment by touhidurrr** [comment]
> Ok
> I added a 'copy stacktrace to clipboard' so in future errors it will be easier to debug

Also, this reminds me of something. I remember that game did not try to upload preview files when the main save file upload failed. Why are we not trying to upload these files in parallel. This should reduce next turn time in multiplayer.

**Comment by yairm210** [comment]
That's a good idea!!
